### ISSUE TITLE
Data Sync and UI Issue

### ISSUE THREAD

**Issue by nickaway000** [tsaxking/template-scouting-app#125]
Data doesn't sync properly during remote scouting, and UI elements like rows and images don't retain their state across views. Additionally, the MatchData.next() function doesn't advance as expected under certain conditions.

**Expected Behavior:**

Data should sync across devices without manual refresh.
UI elements should maintain their state and visibility.
MatchData.next() should correctly advance.

**Steps to Reproduce:**
1. Enable "Remote Scouting" and enter data on multiple devices.
2. Restart the server and observe connection behavior.
3. Navigate through views and check row and image states.

**Suggested Fix:**
1. Implement an automatic reconnection mechanism to maintain connections even after server restarts.
2. Fix UI state management to ensure consistency in row highlighting and image visibility.
3. Optimize the MatchData.next() function to handle all edge cases correctly

**Comment by tsaxking** [comment]
Hi Nickaway. I appreciate the issue. Could you explain what exact steps you took where MatchData.next() does not work properly?
